# Generated by Django 2.2.16 on 2020-11-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='routes',
            field=models.ManyToManyField(blank=True, null=True, related_name='stations', to='bus_navigation.Route'),
        ),
    ]
